name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          version: "lts/*"
      - run: npm i -g awesome-lint
      - run: awesome-lint
